#
# ---------------------------------------------------------------------------
# This source code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# If this code is modified and/or redistributed, please retain this
# header, as well as any other 'flower-box' headers, that are
# contained in the code in order to give credit where credit is due.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# Please use this URL to review the GNU General Public License:
# http://www.gnu.org/licenses/gpl.txt
# ---------------------------------------------------------------------------
#
# hfm -- read xfm source and generate rich text output 
#

# must be set in EVERY mkfile AND in master.mk -- erk.
MKSHELL = ksh		

# these must be set before master is pulled in
#
ALL = libraries pfm
INSTALL =
SCDSRC = 

gflag=

< ../master.mk

NUKE = $NUKE pfm


IFLAGS = -I. -I ../hfm -I ../rfm -I ../lib

pfmlib = librfm$gflag.a

libraries:N: pfm $pfmlib

libs = -L../afileio -lafi -L../lib -lut
libs = -L../hfm -lhfm${gflag:-} -L../rfm -lrfm${gflag:-} -L../afileio -lafi${gflag:-} -L../lib -lut${gflag:-}

# source for the lib
src = fmaddtok fmasis fmbd fmbeglst fmbox fmbxend fmbxst \
	fmccol fmcd fmceject fmcmd fmcpage  \
	fmditem fmdummy fmendlis fmep fmfigure fmflush fmfmt \
	fmformat fmgetpts fmheader fmimbed fmindent fminit fmjustif \
	fmline fmll fmnofmt fmoneject fmpflush  \
	fmrfoot fmright fmrunout fmsetcolour fmsetfon \
	fmsetstr fmsetx fmsety fmspace fmstate fmtable fmtc \
	fmtmpfon fmtmpy fmtoc fmtoksiz fmtopmar fmvartok 

obj = ${src:%=%.o}

$pfmlib(%.o):N:    %.o
$pfmlib:   ${src:%=$pfmlib(%.o)}
	ksh '(
	set -e
	names="${newprereq//$pfmlib\(}"					# pluck off lib.*( from each in newprereq
	ar r $pfmlib ${names//\)/} && rm ${names//\)/}	# archive and remove after ditching trailing ) from each name
	ranlib $pfmlib || true
	)'

pfm:	fmmain.c $obj
	$CC $CFLAGS $IFLAGS -o pfm $obj fmmain.c $libs 



