#
# ---------------------------------------------------------------------------
# This source code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# If this code is modified and/or redistributed, please retain this
# header, as well as any other 'flower-box' headers, that are
# contained in the code in order to give credit where credit is due.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# Please use this URL to review the GNU General Public License:
# http://www.gnu.org/licenses/gpl.txt
# ---------------------------------------------------------------------------
#
# tfm -- read xfm source and generate  text output 
#

# must be set in EVERY mkfile AND in master.mk -- erk.
MKSHELL = ksh		

# these must be set before master is pulled in
#
ALL = tfm libraries
INSTALL =
SCDSRC = 


< ../master.mk
NUKE = $NUKE $ALL


IFLAGS = -I. -I ../hfm -I ../rfm -I ../lib

tfmlib = libtfm$gflag.a

libraries:N: $tfmlib

libs = -L../afileio -lafi -L../lib -lut
libs = -L../hfm -lhfm${gflag:-} -L../rfm -lrfm${gflag:-} -L../afileio -lafi${gflag:-} -L../lib -lut${gflag:-}

# source for the lib
src = fmaddtok fmbd fmbeglst fmbxend fmbxst fmcell fmcmd \
	fmditem fmendlis fmflush fmheader fmignore fminit \
	fmjustif fmline fmlisti fmnofmt fmpara fmtable fmtr 

obj = ${src:%=%.o}

$tfmlib(%.o):N:    %.o
$tfmlib:   ${src:%=$tfmlib(%.o)}
	ksh '(
	set -e
	names="${newprereq//$tfmlib\(}"					# pluck off lib.*( from each in newprereq
	ar r $tfmlib ${names//\)/} && rm ${names//\)/}	# archive and remove after ditching trailing ) from each name
	ranlib $tfmlib || true
	)'

tfm:	fmmain.c $obj
	$CC $CFLAGS $IFLAGS -o tfm $obj fmmain.c $libs 

xtfm:	libraries fmmain.c
	$CC $CFLAGS $IFLAGS -o tfm  fmmain.c $tfmlib $libs 


