/*
* ======================================================================== v1.0/0a157 
*                                                         
*       This software is part of the AT&T Ningaui distribution 
*	
*       Copyright (c) 2001-2009 by AT&T Intellectual Property. All rights reserved
*	AT&T and the AT&T logo are trademarks of AT&T Intellectual Property.
*	
*       Ningaui software is licensed under the Common Public
*       License, Version 1.0  by AT&T Intellectual Property.
*                                                                      
*       A copy of the License is available at    
*       http://www.opensource.org/licenses/cpl1.0.txt             
*                                                                      
*       Information and Software Systems Research               
*       AT&T Labs 
*       Florham Park, NJ                            
*	
*	Send questions, comments via email to ningaui_support@research.att.com.
*	
*                                                                      
* ======================================================================== 0a229
*/

#include	<stdlib.h>
#include	<sfio.h>
#include	<string.h>
#include	"ningaui.h"
#include	"tumbler.man"

int
main(int argc, char **argv)
{
	char *s;
	int peek = 0;
	Tumbler *t;
	int gen = 0;
	int	timeout = 2;		/* timeout for nar_if acks */

	ARGBEGIN{
	case 'g':	IARG(gen); break;
	case 'p':	peek = 1; break;
	case 't':	IARG( timeout ); break;
	case 'v':	OPT_INC(verbose); break;
	default:
usage:
			sfprintf( sfstderr, "Usage: %s [-vp] [-g gen] nvar\n", argv0);
			exit(1);
	}ARGEND
	if(argc != 1){
		goto usage;
	}
	
	ng_nar_to( timeout );			/* set the timeout with narbalek functions */

	if((t = ng_tumbler_init(argv[0])) == 0){
		sfprintf(sfstderr, "%s: cannot initialise tumbler from var %s\n", argv0, argv[0]);
		exit(1);
	}
	s = ng_tumbler(t, 1, peek, gen);		/* only managed left */
	sfprintf(sfstdout, "%s\n", s);

	exit(0);
	return 0;
}


/* ---------- SCD: Self Contained Documentation ------------------- 
&scd_start
&doc_title(ng_tumbler:Generate a Tumbler Filename)

&space
&synop	&this [-v] [-p] [-g off] var

&space
&desc	&This takes a tumbler spec embedded in the pink pages variable &ital(var)
	and returns the next filename on stdout. The new tumbler state is
	updated in &ital(var). With the verbose option, the current tumbler spec
	is written on stderr.
&space
	A tumbler spec is a -tuple with no white space and each component seperated
	by a comma. The fields, from left to right, are &ital(pre), &ital(suf), &ital(nlo),
	&ital(mlo), &ital(nhi), &ital(mhi). A tumbler spec generates a sequence of &ital(mlo)+&ital(mhi)
	filenames of the form &ital(pre)&cw(.)gen&cw(.)&ital(suf). The sequence gen is
	generated by a pair of tumblers (a high frequency and a low frequency), each
	with a current state &ital(n) and a size &ital(m). For example, with
	&ital(nlo)&cw(=50) and &ital(nhi)&cw(=300), the sequence would start
&space
  &cw(b001 b002 b003 ... b299 a001 b001 b002 b003 ... b299 a002)
&space
	with the &cw(a) names wrapping as you would expect
&space
  &cw(a001 a002 ... a049 a000 a001 ...)
&space
&opts	The following options are recognised by &this when placed on the command line:
&begterms
&term	-g off : Set the peek offset, which is otherwise zero. Negative values mean in the past.
&term	-p : Peek at the last value returned, without altering the variable.
&term	-t n : Sets the timeout in seconds to wait for a narbalek ack. 
&term	-v : Verbose. The more, the merrier.
&endterms

&space
&exit

&space
&see

&space
&mods
&owner(Andrew Hume)
&lgterms
&term	6 Jan 2005 (agh) : Fresh from the oven.
&term	11 Sep 2007 (sd) : Added -t option.
&endterms

&scd_end
------------------------------------------------------------------ */
