#
# ---------------------------------------------------------------------------
# This source code is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# If this code is modified and/or redistributed, please retain this
# header, as well as any other 'flower-box' headers, that are
# contained in the code in order to give credit where credit is due.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# Please use this URL to review the GNU General Public License:
# http://www.gnu.org/licenses/gpl.txt
# ---------------------------------------------------------------------------
#
# hfm -- read xfm source and generate html output
#

# must be set in EVERY mkfile AND in master.mk -- erk.
MKSHELL = ksh		

# these must be set before master is pulled in
#
ALL = hfm libraries
INSTALL =
SCDSRC = 

< ../master.mk

NUKE = $NUKE $ALL


IFLAGS = -I. -I ../lib -I ../rfm

hfmlib = libhfm$gflag.a

libraries:N: $hfmlib

libs = -L../rfm -lrfm${gflag:-} -L../afileio -lafi${gflag:-} -L../lib -lut${gflag:-}

# source for the lib
src = fmaddtok fmbd fmbeglst fmbox fmbxend fmbxst fmcd fmceject fmcell \
	fmcenter fmcmd fmcss fmditem fmelse fmendlis \
	fmflush fmheader fmindent fminit fmjustif fmline fmlisti fmll  \
	fmnofmt fmpara fmpflush fmright fmrunset fmsectio fmsetcol fmsetfon \
	fmsetmar fmsetx fmsety fmspace fmtable fmtc fmtoc fmtoksiz fmtr 

obj = ${src:%=%.o}


$hfmlib(%.o):N:    %.o
$hfmlib:   ${src:%=$hfmlib(%.o)}
	ksh '(
	set -e
	names="${newprereq//$hfmlib\(}"					# pluck off lib.*( from each in newprereq
	ar r $hfmlib ${names//\)/} && rm ${names//\)/}	# archive and remove after ditching trailing ) from each name
	ranlib $hfmlib || true
	)'

hfm:	fmmain.c $obj 
	$CC $CFLAGS $IFLAGS -o hfm fmmain.c $obj  $libs 

test2 :: test2.c -lafi -lut



