/*
* ======================================================================== v1.0/0a157 
*                                                         
*       This software is part of the AT&T Ningaui distribution 
*	
*       Copyright (c) 2001-2009 by AT&T Intellectual Property. All rights reserved
*	AT&T and the AT&T logo are trademarks of AT&T Intellectual Property.
*	
*       Ningaui software is licensed under the Common Public
*       License, Version 1.0  by AT&T Intellectual Property.
*                                                                      
*       A copy of the License is available at    
*       http://www.opensource.org/licenses/cpl1.0.txt             
*                                                                      
*       Information and Software Systems Research               
*       AT&T Labs 
*       Florham Park, NJ                            
*	
*	Send questions, comments via email to ningaui_support@research.att.com.
*	
*                                                                      
* ======================================================================== 0a229
*/

/*
----------------------------------------------------------------------------
 Mnemonic:	show_man
 Abstract: 	Expects to find a _man_text array and causes its contents
		to be displayed by the pager listed in the user's enviornment
		or more if none is listed. See SCD at end 
 Date: 		2 April 2001
 Author:	E. Scott Daniels
---------------------------------------------------------------------------
*/
#include	<unistd.h>
#include	<stdio.h>
#include	<stdlib.h>
#include	<sys/types.h>

#include	<sfio.h>
#include	<ningaui.h>

void show_man( )
{
	extern	char	*_man_text[];
	extern	char	*_man2_text[];		/* alternate things like parsers have two pages */
	int i;
	Sfio_t *f;
        char fname[25];
        char cmd[2000];            /* gross but safe */
	char *pager;

	if( ! _man_text )
	{
		sfprintf( sfstderr, "invalid man_text pointer\n" );
		return;
	}

	if( (pager = getenv( "PAGER" )) == NULL )
		pager = "more";

	sprintf( fname, "/tmp/show_man.%d", getpid( ) );
	if((f = ng_sfopen( NULL, fname, "w" )) != NULL )
	{
		for( i = 0; _man_text[i]; i++ )
			sfprintf( f, "%s\n", _man_text[i] );

		if( _man2_text && _man2_text[0] )
		{
			sfprintf( f, "\n" );
			for( i = 0; _man2_text[i]; i++ )
				sfprintf( f, "%s\n", _man2_text[i] );
		}
	
		sfclose( f );

        	sprintf( cmd, "%s %s", pager, fname );
		system( cmd );
		unlink( fname );
	}
	else
	 	fprintf( stderr, "cannot open tmp file: %s\n", fname );
} 


/* ---------- SCD: Self Contained Documentation ------------------- 
&scd_start
&doc_title(ng_show_man:Show Compiled In Manual Page)

&space
&synop	ng_show_man( );

&space
&desc	The &this function provides the means to display
	the manual (man) page for a programme that was created from 
	the Self Contained Documentation (SCD) section of the programme's 
	source code. 
	&ital(Ng_show_man) will copy the strings pointed 
	to by the &lit(_man_text) array to a temporary file, and then 
	arrange for the default &ital(pager) to display the file on 
	the user's tty. It is completely possible that the temporary
	file is actually a pipe to the pager command. If a temporary 
	file was used, it is removed after the contents have been 
	displayed.

&space	The &lit(_man_text) array is an array of pointers to NULL 
	terminated character strings. The last pointer &stress(must)
	be a NULL pointer or unpredictable results will occur when 
	&this attemtps to read the data. 

&subcat Creating The Array
	During compilation, the SCD portion of the programme source
	is compiled using the Termal Fomatter (TFM) component of XFM.
	The document generated by TFM is then converted to initialisation
	statements for the &lit(_man_text) array and saved in a file 
	that can be included using a &lit(#include) directive during 
	the compilation of the programme. 

&subcat	The Pager
	&ital(Ng_show_man) selects the pager programme to display the 
	document based on the contents of the &lit(PAGER) environment
	variable.  If this varible is not set, then the &lit(more) 
	programme will be used. 

&subcat	Invoking This Function
	Generally the programmer does not need to add a specific 
	call to this function.  The &lit(ARGBEGIN) macro
	(&lit(ng_basic.h) contains a test for the &lit(-man) option 
	entered from the command line, and will invoke this routine 
	when it is encountered. 
&space

&space
&see	more(1), pg(1), &manpage(XFM)

&space
&mods
&owner(Scott Daniels)
&lgterms
&term	02 Apr 2001 (sd) : Original code. 
&term	13 Nov 2006 (sd) : Better tmp name.
&term	16 Nov 2006 (sd) : Converted sfopen() to ng_sfopen().
&endterms

&scd_end
*/
